#!/bin/bash

cd /etc/openvpn/easy-rsa
. ./vars
./clean-all
openssl dhparam -out keys/dh2048.pem 2048
./build-ca
export KEY_NAME='prod-vpn'
./build-key-server $KEY_NAME
touch /etc/openvpn/easy-rsa/openvpn-setup.txt
